org: drummer149
app: github-typescript-http-api
service: github-typescript-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  test:
    handler: test.test
    events:
      - httpApi:
          path: /test
          method: get

plugins:
  - serverless-plugin-typescript
